#James Kiernan
#C00125728

EXE=Rendevous
CC=g++
CFLAGS= -std=c++11 -pthread
CFILES=Rendevous.cpp Semaphore.cpp
HFILES=Semaphore.h

ALL: $(CFILES) $(HFILES)
	$(CC) $(CFLAGS) $(CFILES) -o $(EXE)
CLEAN:
	rm *.o
